### PR TITLE
Add Hello Proclub

### PR DESCRIPTION
**Pull request by wisn**
Proclub is now a lab.

### CODE REVIEW

**Comment by pamungkaski** [comment]
Proclub should be ProClub instead of Programming Club i believe

**Comment by wisn** [comment]
Updated @pamungkaski.

**Comment by pamungkaski** [comment]
@wisn K Tho

**Comment by wisn** [comment]
Please wait. This PR is not ready yet to be merged.

**Comment by ceefour** [comment]
waiting for update ..

**Comment by wisn** [comment]
@ceefour Ready to be merged

**Pull request merged**
